package com.tweetapp.tweetservice.model;

import java.util.List;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;
import com.tweetapp.tweetservice.converter.*;

import lombok.Getter;
import lombok.Setter;


@DynamoDBTable(tableName="tweets")
public class Tweets {
	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String tId;
	
	@DynamoDBAttribute
	private String tweet;
	
	@DynamoDBAttribute
	private String userName;
	
	@DynamoDBAttribute
	private String createdDate;
	
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = ReplyConverter.class)
	private List<TweetReply> reply;
	
	@DynamoDBAttribute
	@DynamoDBTypeConverted(converter = LikesConverter.class)
	private List<String> likes;

	public String gettId() {
		return tId;
	}

	public void settId(String tId) {
		this.tId = tId;
	}

	public String getTweet() {
		return tweet;
	}

	public void setTweet(String tweet) {
		this.tweet = tweet;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}

	public List<TweetReply> getReply() {
		return reply;
	}

	public void setReply(List<TweetReply> reply) {
		this.reply = reply;
	}

	public List<String> getLikes() {
		return likes;
	}

	public void setLikes(List<String> likes) {
		this.likes = likes;
	}
	
}
